local _, ns = ...

-- Per-encounter REGIME PROFILES (WO-075 / D-014) — the fight's STRUCTURE that a health curve alone can't
-- convey, consumed by nil-guarded seams in the estimator: `confCap` (where the readout is measurably wrong,
-- cap confidence so the bar goes QUIET rather than showing a confident-wrong countdown), `freeze` (hold the
-- countdown while health truly stalls), `hideBar` (health is pure noise), `suppressFlush` (scripted chunk
-- damage must not trigger the regime-change flush), `resetOnRise` (a phase reset starts a fresh pool).
-- Injected as `opts.regime` behind the frozen estimator API; every field is optional, an absent field is a
-- no-op, and `regime = nil` reproduces the baseline EXACTLY. Kept separate from rhythms.lua so the two
-- pipelines never mix. Dual-keyed classic + WCL-Fresh (+150000).
--
-- AUTO-GENERATED by tools/assemble-regimes.py from the lab's tools/candidates/regime-*.lua (numeric fields
-- learned by tools/learn-regime.py from the estimator's own measured per-bin error on real kills) plus the
-- hand-authored categorical facts in that script. NEVER hand-edit this file — change a fact or re-learn,
-- then re-run the assembler.

-- The universal raid gate — folded into every profile below and returned for un-profiled boss-level
-- targets: raids open slow, so the bar is never certain at/near full health.
local DEFAULT_CONFCAP = { [20] = 0.0, [19] = 0.1 }

local profiles = {
    -- Chromaggus
    [616] = {
        confCap = { [20] = 0.76 },
        kills = 30,
    },
    -- Sulfuron Harbinger — his healers pollute the curve (heals only flatten a monotonic slope, so they are invisible
    -- to health polling). Cap confidence; the CLEU heal add-back is the deferred fix (design §5).
    [669] = {
        confCap = { [20] = 0.72, [19] = 0.09, [18] = 0.86, [17] = 0.96 },
        healPolluted = true, -- reserved for the CLEU tier (inert today)
        kills = 30,
    },
    -- Majordomo Executus — the encounter ends by killing his four Flamewaker adds, not him; his own health is pure
    -- noise. A CLEU add-counter that makes him estimable is a deferred future WO (design §5).
    [671] = {
        hideBar = true,
    },
    -- The Prophet Skeram
    [709] = {
        confCap = {
            [20] = 0.28,
            [19] = 0.9,
            [17] = 0.6,
            [15] = 0.92,
            [14] = 0.05,
            [13] = 0.38,
            [12] = 0.76,
            [10] = 0.48,
            [9] = 0.26,
            [8] = 0.03,
            [7] = 0.07,
            [6] = 0.17,
            [5] = 0.18,
            [4] = 0.0,
            [3] = 0.0,
            [2] = 0.0,
            [1] = 0.0,
        },
        kills = 30,
    },
    -- Viscidus
    [713] = {
        confCap = { [20] = 0.75, [19] = 0.15, [18] = 0.0, [2] = 0.94, [1] = 0.0 },
        kills = 30,
    },
    -- Twin Emperors — two bosses share one health pool readout and swap places; the true remaining pool is not
    -- visible to health polling alone. Reserved for the CLEU/second-pool tier.
    [715] = {
        confCap = 0.46, -- every bin measured unreadable
        secondPool = true, -- reserved for the CLEU tier (inert today)
        kills = 30,
    },
    -- Ouro
    [716] = {
        confCap = { [20] = 0.68 },
        kills = 30,
    },
    -- C'Thun
    [717] = {
        confCap = { [20] = 0.0 },
        kills = 30,
    },
    -- General Rajaxx
    [719] = {
        confCap = { [20] = 0.0, [19] = 0.0, [18] = 0.0, [17] = 0.0, [16] = 0.0, [15] = 0.27 },
        kills = 30,
    },
    -- Buru the Gorger — scripted egg-phase chunk damage fires the two-cliff regime flush on a MECHANIC rather
    -- than a real kill-speed change, discarding a sound prior — suppress the flush, keep folding evidence.
    [721] = {
        suppressFlush = true,
        confCap = {
            [20] = 0.0,
            [19] = 0.0,
            [18] = 0.91,
            [17] = 0.81,
            [16] = 0.58,
            [15] = 0.0,
            [14] = 0.93,
            [13] = 0.98,
            [11] = 0.88,
            [9] = 0.33,
            [8] = 0.88,
            [6] = 0.0,
            [5] = 0.61,
        },
        kills = 30,
    },
    -- Jin'do the Hexxer — healed by adds — same invisible-heal pollution as Sulfuron. Reserved for the CLEU tier.
    [792] = {
        confCap = { [20] = 0.62, [9] = 0.9, [8] = 0.84 },
        healPolluted = true, -- reserved for the CLEU tier (inert today)
        kills = 30,
    },
    -- Onyxia
    [1084] = {
        confCap = { [20] = 0.0, [11] = 0.0, [10] = 0.91, [8] = 0.89, [7] = 0.93 },
        kills = 100,
    },
}

-- Key aliasing (mirrors rhythms.lua): the live client fires the classic DungeonEncounterID in
-- ENCOUNTER_START; WCL's Fresh partition names the same encounter at +150000. Alias both so either
-- reality resolves; the in-game /reload confirms which. `default` is the un-profiled boss fallback.
local regimes = { default = { confCap = DEFAULT_CONFCAP } }
for id, prof in pairs(profiles) do
    regimes[id] = prof
    regimes[id + 150000] = prof
end

ns.Regimes = regimes
