-- Learned regime profile — encounter 150721 (30 kills, TRAIN half of an even/odd split — odd half held out; WO-075). AUTO-GENERATED by
-- tools/learn-regime.py; do not hand-edit. confCap[i] caps CONFIDENCE in health bin i (bin 20 =
-- h in (0.95,1.0], bin 1 = the execute end), learned from the estimator's OWN measured error over real
-- kills: where the readout is measurably wrong the bar goes QUIET (the client hides it below
-- minConfidenceToShow = 0.5) instead of showing a confident-wrong countdown.
return {
    encounterID = 150721,
    kills = 30,
    confCap = { [20] = 0.0, [19] = 0.0, [18] = 0.91, [17] = 0.81, [16] = 0.58, [15] = 0.0, [14] = 0.93, [13] = 0.98, [11] = 0.88, [9] = 0.33, [8] = 0.88, [6] = 0.0, [5] = 0.61 },
}
