-- Learned regime profile — encounter 150709 (30 kills, TRAIN half of an even/odd split — odd half held out; WO-075). AUTO-GENERATED by
-- tools/learn-regime.py; do not hand-edit. confCap[i] caps CONFIDENCE in health bin i (bin 20 =
-- h in (0.95,1.0], bin 1 = the execute end), learned from the estimator's OWN measured error over real
-- kills: where the readout is measurably wrong the bar goes QUIET (the client hides it below
-- minConfidenceToShow = 0.5) instead of showing a confident-wrong countdown.
return {
    encounterID = 150709,
    kills = 30,
    confCap = { [20] = 0.28, [19] = 0.9, [17] = 0.6, [15] = 0.92, [14] = 0.05, [13] = 0.38, [12] = 0.76, [10] = 0.48, [9] = 0.26, [8] = 0.03, [7] = 0.07, [6] = 0.17, [5] = 0.18, [4] = 0.0, [3] = 0.0, [2] = 0.0, [1] = 0.0 },
}
