-- Learned regime profile — encounter 150715 (30 kills, TRAIN half of an even/odd split — odd half held out; WO-075). AUTO-GENERATED by
-- tools/learn-regime.py; do not hand-edit. confCap[i] caps CONFIDENCE in health bin i (bin 20 =
-- h in (0.95,1.0], bin 1 = the execute end), learned from the estimator's OWN measured error over real
-- kills: where the readout is measurably wrong the bar goes QUIET (the client hides it below
-- minConfidenceToShow = 0.5) instead of showing a confident-wrong countdown.
return {
    encounterID = 150715,
    kills = 30,
    confCap = { [20] = 0.0, [19] = 0.0, [18] = 0.0, [17] = 0.0, [16] = 0.0, [15] = 0.0, [14] = 0.0, [13] = 0.0, [12] = 0.0, [11] = 0.0, [10] = 0.0, [9] = 0.0, [8] = 0.0, [7] = 0.0, [6] = 0.0, [5] = 0.0, [4] = 0.0, [3] = 0.0, [2] = 0.0, [1] = 0.46 },
}
