-- Learned regime profile — encounter 150717 (30 kills, TRAIN half of an even/odd split — odd half held out; WO-075). AUTO-GENERATED by
-- tools/learn-regime.py; do not hand-edit. confCap[i] caps CONFIDENCE in health bin i (bin 20 =
-- h in (0.95,1.0], bin 1 = the execute end), learned from the estimator's OWN measured error over real
-- kills: where the readout is measurably wrong the bar goes QUIET (the client hides it below
-- minConfidenceToShow = 0.5) instead of showing a confident-wrong countdown.
return {
    encounterID = 150717,
    kills = 30,
    confCap = { [20] = 0.0 },
}
