-- Learned regime profile — encounter 150789 (30 kills, TRAIN half of an even/odd split — odd half held out; WO-075). AUTO-GENERATED by
-- tools/learn-regime.py; do not hand-edit. confCap[i] caps CONFIDENCE in health bin i (bin 20 =
-- h in (0.95,1.0], bin 1 = the execute end), learned from the estimator's OWN measured error over real
-- kills: where the readout is measurably wrong the bar goes QUIET (the client hides it below
-- minConfidenceToShow = 0.5) instead of showing a confident-wrong countdown.
return {
    encounterID = 150789,
    kills = 30,
    confCap = { [20] = 0.0, [19] = 0.35, [18] = 0.33, [17] = 0.18, [16] = 0.37, [15] = 0.23, [14] = 0.28, [13] = 0.3, [12] = 0.35, [11] = 0.24, [10] = 0.33, [9] = 0.16, [8] = 0.25, [7] = 0.16, [6] = 0.0, [5] = 0.08, [4] = 0.0, [3] = 0.0, [2] = 0.0, [1] = 0.0 },
    resetOnRise = 0.25,
}
